import { VenueOrEvent, Special, Itinerary } from "./types";

export const heroItems: VenueOrEvent[] = [
  {
    id: "jazz-alley",
    name: "Jazz Alley",
    subtitle: "Live jazz in an intimate supper club setting",
    neighborhood: "Belltown",
    price: "$$$",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    time: "Tonight 8pm",
    rationale: "Seattle's best live jazz — two sets, great cocktails, no cover charge tonight",
    type: "venue",
    relatedPlanIds: ["plan-dinner-jazz", "plan-jazz-nightcap"],
  },
  {
    id: "canon",
    name: "Canon",
    subtitle: "Award-winning whiskey bar with 4,000+ bottles",
    neighborhood: "Capitol Hill",
    price: "$$$",
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80",
    time: "Open until 2am",
    rationale: "World's largest whiskey selection — perfect for a serious drink night",
    type: "venue",
    relatedPlanIds: ["plan-drinks-club", "plan-jazz-nightcap", "plan-dessert-drinks"],
  },
  {
    id: "rays-boathouse",
    name: "Ray's Boathouse",
    subtitle: "Pacific Northwest seafood with waterfront views",
    neighborhood: "Ballard",
    price: "$$$",
    imageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    time: "Dinner 5–10pm",
    rationale: "Sunset views over Shilshole Bay — best seafood in the city tonight",
    type: "venue",
    relatedPlanIds: ["plan-seafood-sunset", "plan-dinner-jazz", "plan-brunch-walk"],
  },
];

export const trendingItems: VenueOrEvent[] = [
  {
    id: "crocodile",
    name: "The Crocodile",
    subtitle: "Indie rock show — doors at 7pm",
    neighborhood: "Belltown",
    price: "$$",
    imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80",
    time: "Tonight 8pm",
    rationale: "One of Seattle's most iconic music venues",
    type: "event",
    relatedPlanIds: [],
  },
  {
    id: "gas-works-sunset",
    name: "Gas Works Park Sunset",
    subtitle: "Golden hour views over Lake Union",
    neighborhood: "Wallingford",
    price: "Free",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    time: "Tonight 7:42pm",
    rationale: "Clear skies tonight — best free view in the city",
    type: "experience",
    relatedPlanIds: [],
  },
  {
    id: "spinasse",
    name: "Spinasse",
    subtitle: "Northern Italian pasta, handmade daily",
    neighborhood: "Capitol Hill",
    price: "$$$",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    time: "Dinner until 10pm",
    rationale: "Reservation just opened up — grab it",
    type: "venue",
    relatedPlanIds: [],
  },
  {
    id: "vermillion",
    name: "Vermillion",
    subtitle: "Art bar with rotating gallery shows",
    neighborhood: "Capitol Hill",
    price: "$",
    imageUrl: "https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800&q=80",
    time: "Open until 2am",
    rationale: "New show opening tonight with free wine",
    type: "event",
    relatedPlanIds: [],
  },
  {
    id: "pike-place",
    name: "Pike Place Market",
    subtitle: "Late-night wander + oysters at the bar",
    neighborhood: "Downtown",
    price: "$$",
    imageUrl: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&q=80",
    time: "Until 9pm",
    rationale: "Evening crowd, street food, and a drink at the bar",
    type: "experience",
    relatedPlanIds: [],
  },
];

export const specials: Special[] = [
  {
    id: "spec-1",
    venueName: "Bar Sajor",
    offerTitle: "Happy hour oysters — $1.50 each",
    validityWindow: "Tonight 4–6pm",
    urgencyLabel: "Ends in 45 min",
    cta: "Get details",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    neighborhood: "Pioneer Square",
  },
  {
    id: "spec-2",
    venueName: "Radiator Whiskey",
    offerTitle: "Free charcuterie with any cocktail",
    validityWindow: "Tonight until 7pm",
    urgencyLabel: "Tonight only",
    cta: "Reserve",
    imageUrl: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80",
    neighborhood: "Pike Place",
  },
  {
    id: "spec-3",
    venueName: "Cafe Solstice",
    offerTitle: "Late night espresso pop-up",
    validityWindow: "10pm – midnight",
    urgencyLabel: "Limited seats",
    cta: "Order",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
    neighborhood: "Capitol Hill",
  },
  {
    id: "spec-4",
    venueName: "The Pink Door",
    offerTitle: "Rooftop lounge opens at sunset",
    validityWindow: "Tonight 7–11pm",
    urgencyLabel: "Weather-dependent",
    cta: "Directions",
    imageUrl: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    neighborhood: "Pike Place",
  },
];

export const easyWins: VenueOrEvent[] = [
  {
    id: "kalbi-burger",
    name: "Rancho Bravo Tacos",
    subtitle: "No-fuss late-night tacos",
    neighborhood: "Capitol Hill",
    price: "$",
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    time: "Open until 3am",
    rationale: "Always good, always open, always worth it",
    type: "venue",
    relatedPlanIds: [],
  },
  {
    id: "linda-lounge",
    name: "Linda's Tavern",
    subtitle: "Chill neighborhood bar with a patio",
    neighborhood: "Capitol Hill",
    price: "$",
    imageUrl: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80",
    time: "Open until 2am",
    rationale: "No attitude, great jukebox, easy to show up solo or with friends",
    type: "venue",
    relatedPlanIds: [],
  },
  {
    id: "movies-fremont",
    name: "Fremont Outdoor Cinema",
    subtitle: "Cult classic screening tonight",
    neighborhood: "Fremont",
    price: "$",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    time: "Starts 9pm",
    rationale: "BYOB, blankets welcome — zero effort, max fun",
    type: "event",
    relatedPlanIds: [],
  },
];

export const readyMadePlans: Itinerary[] = [
  {
    id: "plan-drinks-club",
    title: "Drinks + Club",
    summary: "Start the night with cocktails, end it on the dance floor",
    duration: "~4 hrs",
    priceBand: "$40–60/person",
    stops: [
      { name: "Canon", time: "9pm", neighborhood: "Capitol Hill" },
      { name: "Queer Bar", time: "10:30pm", neighborhood: "Capitol Hill" },
      { name: "Neighbours", time: "Midnight", neighborhood: "Capitol Hill" },
    ],
    tags: ["Nightlife", "Dancing"],
  },
  {
    id: "plan-dinner-jazz",
    title: "Dinner + Jazz",
    summary: "A proper evening — great food, then live music",
    duration: "~3.5 hrs",
    priceBand: "$70–100/person",
    stops: [
      { name: "Spinasse", time: "6:30pm", neighborhood: "Capitol Hill" },
      { name: "Jazz Alley", time: "8pm", neighborhood: "Belltown" },
    ],
    tags: ["Date night", "Live music"],
  },
  {
    id: "plan-jazz-nightcap",
    title: "Jazz + Nightcap",
    summary: "Catch live music then wind down with a great drink",
    duration: "~3 hrs",
    priceBand: "$50–80/person",
    stops: [
      { name: "Jazz Alley", time: "7:30pm", neighborhood: "Belltown" },
      { name: "Canon", time: "10pm", neighborhood: "Capitol Hill" },
    ],
    tags: ["Chill", "Live music"],
  },
  {
    id: "plan-brunch-walk",
    title: "Brunch + Walk",
    summary: "A slow morning — good food, then some fresh air",
    duration: "~2.5 hrs",
    priceBand: "$20–35/person",
    stops: [
      { name: "Toulouse Petit", time: "10:30am", neighborhood: "Queen Anne" },
      { name: "Gas Works Park", time: "12:30pm", neighborhood: "Wallingford" },
    ],
    tags: ["Weekend", "Outdoors"],
  },
  {
    id: "plan-dessert-drinks",
    title: "Dessert + Late-night Drinks",
    summary: "Sweet start, strong finish",
    duration: "~2 hrs",
    priceBand: "$30–50/person",
    stops: [
      { name: "Fuji Bakery", time: "8:30pm", neighborhood: "International District" },
      { name: "Radiator Whiskey", time: "9:30pm", neighborhood: "Pike Place" },
    ],
    tags: ["Low-key", "Date night"],
  },
  {
    id: "plan-seafood-sunset",
    title: "Seafood + Sunset",
    summary: "Watch the sun go down over the water, then dine well",
    duration: "~3 hrs",
    priceBand: "$60–90/person",
    stops: [
      { name: "Gas Works Park", time: "7:00pm", neighborhood: "Wallingford" },
      { name: "Ray's Boathouse", time: "8:30pm", neighborhood: "Ballard" },
    ],
    tags: ["Scenic", "Special occasion"],
  },
];
